In [1]:
# 4*3^n where n is odd
import numpy as np
from collections import Counter

new_matrix=[]
expanded_matrix=[]

def Construct_odd(M):
    global new_matrix
    global expanded_matrix
    a = 1
    b = 2

    A = np.array([[a, a, a],
                  [a, a, a],
                  [a, a, a]])

    B = np.array([[b, -a, a],
                  [a, b, -a],
                  [-a, a, b]])

    
    def negate_matrix(matrix):
        return np.vectorize(lambda x: -x)(matrix)

    m_rows, m_cols = M.shape
    a_rows, a_cols = A.shape
    b_rows, b_cols = B.shape

    assert A.shape == B.shape, "Matrices A and B must have the same shape."

    expanded_matrix = np.empty((m_rows * a_rows, m_cols * a_cols), dtype=int)

    for i in range(m_rows):
        for j in range(m_cols):
            if M[i, j] == 'a':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = A
            elif M[i, j] == '-a':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = negate_matrix(A)
            elif M[i, j] == 'b':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = B
            elif M[i, j] == '-b':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = negate_matrix(B)

    print("Expanded matrix:")
    print(expanded_matrix)

    def substitute_value(value):
        if value == 1:
            return 'a'
        elif value == -1:
            return '-a'
        elif value == 2:
            return 'b'
        elif value == -2:
            return '-b'
        else:
            return value

    new_matrix = np.vectorize(substitute_value)(expanded_matrix)

    print("New matrix:")
    print(new_matrix)
    
M = np.array([['a', 'b','b','b'],
              ['-b', 'a','b','-b'],th
              ['-b', '-b','a','b'],
              ['-b', 'b','-b','a']])

Construct_odd(M)

Expanded matrix:
[[ 1  1  1  2 -1  1  2 -1  1  2 -1  1]
 [ 1  1  1  1  2 -1  1  2 -1  1  2 -1]
 [ 1  1  1 -1  1  2 -1  1  2 -1  1  2]
 [-2  1 -1  1  1  1  2 -1  1 -2  1 -1]
 [-1 -2  1  1  1  1  1  2 -1 -1 -2  1]
 [ 1 -1 -2  1  1  1 -1  1  2  1 -1 -2]
 [-2  1 -1 -2  1 -1  1  1  1  2 -1  1]
 [-1 -2  1 -1 -2  1  1  1  1  1  2 -1]
 [ 1 -1 -2  1 -1 -2  1  1  1 -1  1  2]
 [-2  1 -1  2 -1  1 -2  1 -1  1  1  1]
 [-1 -2  1  1  2 -1 -1 -2  1  1  1  1]
 [ 1 -1 -2 -1  1  2  1 -1 -2  1  1  1]]
New matrix:
[['a' 'a' 'a' 'b' '-a' 'a' 'b' '-a' 'a' 'b' '-a' 'a']
 ['a' 'a' 'a' 'a' 'b' '-a' 'a' 'b' '-a' 'a' 'b' '-a']
 ['a' 'a' 'a' '-a' 'a' 'b' '-a' 'a' 'b' '-a' 'a' 'b']
 ['-b' 'a' '-a' 'a' 'a' 'a' 'b' '-a' 'a' '-b' 'a' '-a']
 ['-a' '-b' 'a' 'a' 'a' 'a' 'a' 'b' '-a' '-a' '-b' 'a']
 ['a' '-a' '-b' 'a' 'a' 'a' '-a' 'a' 'b' 'a' '-a' '-b']
 ['-b' 'a' '-a' '-b' 'a' '-a' 'a' 'a' 'a' 'b' '-a' 'a']
 ['-a' '-b' 'a' '-a' '-b' 'a' 'a' 'a' 'a' 'a' 'b' '-a']
 ['a' '-a' '-b' 'a' '-a' '-b' 'a' 'a' 'a' '-a' 'a' 'b']
 ['-

In [2]:
def Count_odd():

    def count_net_elements(row):
        element_count = Counter(row)
        net_count_a = element_count.get(1, 0) - element_count.get(-1, 0)
        net_count_b = element_count.get(2, 0) - element_count.get(-2, 0)
        return {'a': net_count_a, 'b': net_count_b}

    net_counts = np.apply_along_axis(count_net_elements, axis=1, arr=expanded_matrix)

    for i, counts in enumerate(net_counts):
        print(f"Row {i+1}:",end=" ")
        for element, count in counts.items():
            print(f" {count}{element}",end=" ")

        print()

Count_odd()

Row 1:  3a  3b 
Row 2:  3a  3b 
Row 3:  3a  3b 
Row 4:  3a  -1b 
Row 5:  3a  -1b 
Row 6:  3a  -1b 
Row 7:  3a  -1b 
Row 8:  3a  -1b 
Row 9:  3a  -1b 
Row 10:  3a  -1b 
Row 11:  3a  -1b 
Row 12:  3a  -1b 


In [3]:
new_matrix.shape

(12, 12)

In [4]:
# 4*3^n where n is even
def Construct_even(M):
    
    global expanded_matrix
    global new_matrix
    a = 2
    b = 1

    A = np.array([[a, a, a],
                  [a, a, a],
                  [a, a, a]])

    B = np.array([[b, -a, a],
                  [a, b, -a],
                  [-a, a, b]])

    def negate_matrix(matrix):
        return np.vectorize(lambda x: -x)(matrix)

    m_rows, m_cols = M.shape
    a_rows, a_cols = A.shape
    b_rows, b_cols = B.shape

    assert A.shape == B.shape, "Matrices A and B must have the same shape."

   
    expanded_matrix = np.empty((m_rows * a_rows, m_cols * a_cols), dtype=int)

    
    for i in range(m_rows):
        for j in range(m_cols):
            if M[i, j] == 'a':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = B
            elif M[i, j] == '-a':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = negate_matrix(B)
            elif M[i, j] == 'b':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = A
            elif M[i, j] == '-b':
                expanded_matrix[i*a_rows:(i+1)*a_rows, j*a_cols:(j+1)*a_cols] = negate_matrix(A)

    print("Expanded matrix:")
    print(expanded_matrix)

    def substitute_value(value):
        if value == 1:
            return 'a'
        elif value == -1:
            return '-a'
        elif value == 2:
            return 'b'
        elif value == -2:
            return '-b'
        else:
            return value

    new_matrix = np.vectorize(substitute_value)(expanded_matrix)

    print("New matrix:")
    print(new_matrix)



In [5]:
M = new_matrix
Construct_even(M)
new_matrix.shape

Expanded matrix:
[[ 1 -2  2 ...  1 -2  2]
 [ 2  1 -2 ...  2  1 -2]
 [-2  2  1 ... -2  2  1]
 ...
 [ 1 -2  2 ...  1 -2  2]
 [ 2  1 -2 ...  2  1 -2]
 [-2  2  1 ... -2  2  1]]
New matrix:
[['a' '-b' 'b' ... 'a' '-b' 'b']
 ['b' 'a' '-b' ... 'b' 'a' '-b']
 ['-b' 'b' 'a' ... '-b' 'b' 'a']
 ...
 ['a' '-b' 'b' ... 'a' '-b' 'b']
 ['b' 'a' '-b' ... 'b' 'a' '-b']
 ['-b' 'b' 'a' ... '-b' 'b' 'a']]


(36, 36)

In [6]:
def Count_even():
    def count_net_elements(row):
        element_count = Counter(row)
        net_count_a = element_count.get(1, 0) - element_count.get(-1, 0)
        net_count_b = element_count.get(2, 0) - element_count.get(-2, 0)
        return {'a': net_count_a, 'b': net_count_b}

    net_counts = np.apply_along_axis(count_net_elements, axis=1, arr=expanded_matrix)

    for i, counts in enumerate(net_counts):
        print(f"Row {i+1}:",end=" ")
        for element, count in counts.items():
            print(f" {count}{element}",end=" ")

        print()

Count_even()

Row 1:  3a  9b 
Row 2:  3a  9b 
Row 3:  3a  9b 
Row 4:  3a  9b 
Row 5:  3a  9b 
Row 6:  3a  9b 
Row 7:  3a  9b 
Row 8:  3a  9b 
Row 9:  3a  9b 
Row 10:  3a  -3b 
Row 11:  3a  -3b 
Row 12:  3a  -3b 
Row 13:  3a  -3b 
Row 14:  3a  -3b 
Row 15:  3a  -3b 
Row 16:  3a  -3b 
Row 17:  3a  -3b 
Row 18:  3a  -3b 
Row 19:  3a  -3b 
Row 20:  3a  -3b 
Row 21:  3a  -3b 
Row 22:  3a  -3b 
Row 23:  3a  -3b 
Row 24:  3a  -3b 
Row 25:  3a  -3b 
Row 26:  3a  -3b 
Row 27:  3a  -3b 
Row 28:  3a  -3b 
Row 29:  3a  -3b 
Row 30:  3a  -3b 
Row 31:  3a  -3b 
Row 32:  3a  -3b 
Row 33:  3a  -3b 
Row 34:  3a  -3b 
Row 35:  3a  -3b 
Row 36:  3a  -3b 


In [7]:
new_matrix.shape

(36, 36)

In [8]:
M = new_matrix
Construct_odd(M)

Expanded matrix:
[[ 1  1  1 ...  2 -1  1]
 [ 1  1  1 ...  1  2 -1]
 [ 1  1  1 ... -1  1  2]
 ...
 [-2  1 -1 ...  1  1  1]
 [-1 -2  1 ...  1  1  1]
 [ 1 -1 -2 ...  1  1  1]]
New matrix:
[['a' 'a' 'a' ... 'b' '-a' 'a']
 ['a' 'a' 'a' ... 'a' 'b' '-a']
 ['a' 'a' 'a' ... '-a' 'a' 'b']
 ...
 ['-b' 'a' '-a' ... 'a' 'a' 'a']
 ['-a' '-b' 'a' ... 'a' 'a' 'a']
 ['a' '-a' '-b' ... 'a' 'a' 'a']]


In [9]:
new_matrix.shape

(108, 108)

In [10]:
Count_odd()

Row 1:  9a  9b 
Row 2:  9a  9b 
Row 3:  9a  9b 
Row 4:  9a  9b 
Row 5:  9a  9b 
Row 6:  9a  9b 
Row 7:  9a  9b 
Row 8:  9a  9b 
Row 9:  9a  9b 
Row 10:  9a  9b 
Row 11:  9a  9b 
Row 12:  9a  9b 
Row 13:  9a  9b 
Row 14:  9a  9b 
Row 15:  9a  9b 
Row 16:  9a  9b 
Row 17:  9a  9b 
Row 18:  9a  9b 
Row 19:  9a  9b 
Row 20:  9a  9b 
Row 21:  9a  9b 
Row 22:  9a  9b 
Row 23:  9a  9b 
Row 24:  9a  9b 
Row 25:  9a  9b 
Row 26:  9a  9b 
Row 27:  9a  9b 
Row 28:  9a  -3b 
Row 29:  9a  -3b 
Row 30:  9a  -3b 
Row 31:  9a  -3b 
Row 32:  9a  -3b 
Row 33:  9a  -3b 
Row 34:  9a  -3b 
Row 35:  9a  -3b 
Row 36:  9a  -3b 
Row 37:  9a  -3b 
Row 38:  9a  -3b 
Row 39:  9a  -3b 
Row 40:  9a  -3b 
Row 41:  9a  -3b 
Row 42:  9a  -3b 
Row 43:  9a  -3b 
Row 44:  9a  -3b 
Row 45:  9a  -3b 
Row 46:  9a  -3b 
Row 47:  9a  -3b 
Row 48:  9a  -3b 
Row 49:  9a  -3b 
Row 50:  9a  -3b 
Row 51:  9a  -3b 
Row 52:  9a  -3b 
Row 53:  9a  -3b 
Row 54:  9a  -3b 
Row 55:  9a  -3b 
Row 56:  9a  -3b 
Row 57:  9a  -3b 
Row 58:  9

In [11]:
new_matrix.shape

(108, 108)

In [12]:
def substitute_value(value):
        if value == 'a':
            return 1
        elif value == '-a':
            return -1
        elif value == 'b':
            return 1
        elif value == '-b':
            return -1
        else:
            return value

new_matrixH = np.vectorize(substitute_value)(new_matrix)
print("Row Sums: ")
print(np.sum(new_matrixH,axis=1))
print("Column Sums: ")
print(np.sum(new_matrixH,axis=0))


Row Sums: 
[18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18 18  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6]
Column Sums: 
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12]


In [13]:
import numpy as np

def find_zero_sum_rows_cols(matrix):
   

    row_sums = np.sum(matrix, axis=1)  

    column_sums = np.sum(matrix, axis=0)

    zero_sum_rows = np.where(np.isclose(row_sums, 0))[0]
    
    zero_sum_columns = np.where(np.isclose(column_sums, 0))[0]
    
    return zero_sum_rows, zero_sum_columns


matrix = new_matrixH
zero_sum_rows, zero_sum_columns = find_zero_sum_rows_cols(matrix)


print(f"Number of rows with sum 0: {len(zero_sum_rows)}")
print(f"Rows with sum 0: {zero_sum_rows.tolist()}")
print(f"Number of columns with sum 0: {len(zero_sum_columns)}")
print(f"Columns with sum 0: {zero_sum_columns.tolist()}")


Number of rows with sum 0: 0
Rows with sum 0: []
Number of columns with sum 0: 27
Columns with sum 0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [45]:
import numpy as np

def find_zero_sum_columns(matrix):
    matrix = np.array(matrix)  # Ensure the input is converted to a NumPy array

    # Calculate column sums
    column_sums = np.sum(matrix, axis=0)
    
    # Find columns with sum 0
    zero_sum_columns = np.where(column_sums == 0)[0]
    
    return zero_sum_columns

# Example matrix
matrix = new_matrixH

# Find zero-sum columns
zero_sum_columns = find_zero_sum_columns(matrix)

# Print the results
print(f"Number of columns with sum 0: {len(zero_sum_columns)}")
print(f"Columns with sum 0: {zero_sum_columns.tolist()}")


Number of columns with sum 0: 0
Columns with sum 0: []


In [12]:
M=new_matrix
Construct_even(M)

Expanded matrix:
[[ 1 -2  2 ...  1 -2  2]
 [ 2  1 -2 ...  2  1 -2]
 [-2  2  1 ... -2  2  1]
 ...
 [ 1 -2  2 ...  1 -2  2]
 [ 2  1 -2 ...  2  1 -2]
 [-2  2  1 ... -2  2  1]]
New matrix:
[['a' '-b' 'b' ... 'a' '-b' 'b']
 ['b' 'a' '-b' ... 'b' 'a' '-b']
 ['-b' 'b' 'a' ... '-b' 'b' 'a']
 ...
 ['a' '-b' 'b' ... 'a' '-b' 'b']
 ['b' 'a' '-b' ... 'b' 'a' '-b']
 ['-b' 'b' 'a' ... '-b' 'b' 'a']]


In [13]:
new_matrix.shape

(324, 324)

In [14]:
Count_odd()

Row 1:  9a  9b 
Row 2:  9a  9b 
Row 3:  9a  9b 
Row 4:  9a  9b 
Row 5:  9a  9b 
Row 6:  9a  9b 
Row 7:  9a  9b 
Row 8:  9a  9b 
Row 9:  9a  9b 
Row 10:  9a  9b 
Row 11:  9a  9b 
Row 12:  9a  9b 
Row 13:  9a  9b 
Row 14:  9a  9b 
Row 15:  9a  9b 
Row 16:  9a  9b 
Row 17:  9a  9b 
Row 18:  9a  9b 
Row 19:  9a  9b 
Row 20:  9a  9b 
Row 21:  9a  9b 
Row 22:  9a  9b 
Row 23:  9a  9b 
Row 24:  9a  9b 
Row 25:  9a  9b 
Row 26:  9a  9b 
Row 27:  9a  9b 
Row 28:  9a  9b 
Row 29:  9a  9b 
Row 30:  9a  9b 
Row 31:  9a  9b 
Row 32:  9a  9b 
Row 33:  9a  9b 
Row 34:  9a  9b 
Row 35:  9a  9b 
Row 36:  9a  9b 
Row 37:  9a  9b 
Row 38:  9a  9b 
Row 39:  9a  9b 
Row 40:  9a  9b 
Row 41:  9a  9b 
Row 42:  9a  9b 
Row 43:  9a  9b 
Row 44:  9a  9b 
Row 45:  9a  9b 
Row 46:  9a  9b 
Row 47:  9a  9b 
Row 48:  9a  9b 
Row 49:  9a  9b 
Row 50:  9a  9b 
Row 51:  9a  9b 
Row 52:  9a  9b 
Row 53:  9a  9b 
Row 54:  9a  9b 
Row 55:  9a  9b 
Row 56:  9a  9b 
Row 57:  9a  9b 
Row 58:  9a  9b 
Row 59:  9a  9b 
Row 60

In [15]:
M = new_matrix
Construct_odd(M)


Expanded matrix:
[[ 1  1  1 ...  2 -1  1]
 [ 1  1  1 ...  1  2 -1]
 [ 1  1  1 ... -1  1  2]
 ...
 [-2  1 -1 ...  1  1  1]
 [-1 -2  1 ...  1  1  1]
 [ 1 -1 -2 ...  1  1  1]]
New matrix:
[['a' 'a' 'a' ... 'b' '-a' 'a']
 ['a' 'a' 'a' ... 'a' 'b' '-a']
 ['a' 'a' 'a' ... '-a' 'a' 'b']
 ...
 ['-b' 'a' '-a' ... 'a' 'a' 'a']
 ['-a' '-b' 'a' ... 'a' 'a' 'a']
 ['a' '-a' '-b' ... 'a' 'a' 'a']]


In [17]:
new_matrix.shape
Count_odd()

Row 1:  27a  9b 
Row 2:  27a  9b 
Row 3:  27a  9b 
Row 4:  27a  9b 
Row 5:  27a  9b 
Row 6:  27a  9b 
Row 7:  27a  9b 
Row 8:  27a  9b 
Row 9:  27a  9b 
Row 10:  27a  9b 
Row 11:  27a  9b 
Row 12:  27a  9b 
Row 13:  27a  9b 
Row 14:  27a  9b 
Row 15:  27a  9b 
Row 16:  27a  9b 
Row 17:  27a  9b 
Row 18:  27a  9b 
Row 19:  27a  9b 
Row 20:  27a  9b 
Row 21:  27a  9b 
Row 22:  27a  9b 
Row 23:  27a  9b 
Row 24:  27a  9b 
Row 25:  27a  9b 
Row 26:  27a  9b 
Row 27:  27a  9b 
Row 28:  27a  9b 
Row 29:  27a  9b 
Row 30:  27a  9b 
Row 31:  27a  9b 
Row 32:  27a  9b 
Row 33:  27a  9b 
Row 34:  27a  9b 
Row 35:  27a  9b 
Row 36:  27a  9b 
Row 37:  27a  9b 
Row 38:  27a  9b 
Row 39:  27a  9b 
Row 40:  27a  9b 
Row 41:  27a  9b 
Row 42:  27a  9b 
Row 43:  27a  9b 
Row 44:  27a  9b 
Row 45:  27a  9b 
Row 46:  27a  9b 
Row 47:  27a  9b 
Row 48:  27a  9b 
Row 49:  27a  9b 
Row 50:  27a  9b 
Row 51:  27a  9b 
Row 52:  27a  9b 
Row 53:  27a  9b 
Row 54:  27a  9b 
Row 55:  27a  9b 
Row 56:  27a  9b 
R

Number of rows with sum 0: 0
Number of columns with sum 0: 0


array([[ 1,  1,  1, ...,  2, -1,  1],
       [ 1,  1,  1, ...,  1,  2, -1],
       [ 1,  1,  1, ..., -1,  1,  2],
       ...,
       [-2,  1, -1, ...,  1,  1,  1],
       [-1, -2,  1, ...,  1,  1,  1],
       [ 1, -1, -2, ...,  1,  1,  1]])